### ISSUE TITLE
get a error

### ISSUE THREAD

**Issue by Ethancck** [FSecureLABS/Jandroid#1]
name 'AnalyzeDEX' is not defined.

**Comment by projectbtle** [comment]
Could you try with a `.apk`, just to see if it gives a similar error for `AnalyzeAPK`?

**Comment by projectbtle** [comment]
Also, which version of Androguard are you using?

**Comment by projectbtle** [comment]
Issue was with incorrect API name. 

If you don't want to re-download Jandroid, you can make a small change in `src/plugins/android/app_analyser.py`. Find and change `AnalyzeDEX` to `AnalyzeDex`.
