### ISSUE TITLE
WARNING  Error analysing 5.dex: [AnalyzeDEXError] name 'AnalyzeDEX' is not defined.

### ISSUE THREAD

**Issue by wyu0hop** [FSecureLABS/Jandroid#4]
Hello,I want to analysis Multidex,but something wrong happened.

----------------------------
           JANDROID
----------------------------

INFO     Creating template object.
INFO     1 potential template(s) found.
DEBUG    Parsing /Users/Desktop/tools/android/Jandroid/templates/android/sample_basic_browsable_jsbridge.template
INFO     Initiating Android analysis.
INFO     Performing basic checks. Please wait.
INFO     Basic checks complete.
INFO     Beginning analysis...
DEBUG    8 app(s) to analyse, using 2 thread(s).
DEBUG    Created worker process 0
DEBUG    Created worker process 1
INFO     Analysing 5.dex in worker thread 1.
INFO     Analysing 4.dex in worker thread 0.
WARNING  Error analysing 5.dex: [AnalyzeDEXError] name 'AnalyzeDEX' is not defined.
WARNING  Error analysing 4.dex: [AnalyzeDEXError] name 'AnalyzeDEX' is not defined.
INFO     Analysing 2.dex in worker thread 0.
WARNING  Error analysing 2.dex: [AnalyzeDEXError] name 'AnalyzeDEX' is not defined.
INFO     Analysing 6.dex in worker thread 1.
WARNING  Error analysing 6.dex: [AnalyzeDEXError] name 'AnalyzeDEX' is not defined.
INFO     Analysing 3.dex in worker thread 0.
WARNING  Error analysing 3.dex: [AnalyzeDEXError] name 'AnalyzeDEX' is not defined.
INFO     Analysing 1.dex in worker thread 1.
WARNING  Error analysing 1.dex: [AnalyzeDEXError] name 'AnalyzeDEX' is not defined.
INFO     Analysing 0.dex in worker thread 0.
WARNING  Error analysing 0.dex: [AnalyzeDEXError] name 'AnalyzeDEX' is not defined.
INFO     Analysing 8.dex in worker thread 1.
WARNING  Error analysing 8.dex: [AnalyzeDEXError] name 'AnalyzeDEX' is not defined.
INFO     Finished analysing apps.
INFO     Creating custom graph.
INFO     Custom graph can be found at /Users/Desktop/tools/android/Jandroid/output/graph/jandroid.html
INFO     All done.

**Comment by projectbtle** [comment]
Which version of Androguard are you using?

**Comment by projectbtle** [comment]
Please see #1
